name: Test Nipe on Ubuntu
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt install -y perl cpanminus gcc make
        sudo cpanm --installdeps .
        sudo perl nipe.pl install
    - name: Verify Nipe status
      run: |
        sudo perl nipe.pl status
